### ISSUE TITLE
Use default slot props to get Canvas context

### ISSUE THREAD

**Issue by alvarosabu** [Tresjs/tres#572] opened 2024-03-04 17:34 UTC
### Description

Idea from @userquin, the idea would be to use [Vue named scoped slots ](https://vuejs.org/guide/components/slots.html#named-scoped-slots) to be able to get the canvas context on the parent like this:

```html
<TresCanvas shadows alpha v-slot="state">
  <TresPerspectiveCamera :position="[5, 5, 5]" />
  <TresOrbitControls
    v-if="state?.renderer"
    :args="[state?.camera, state?.renderer?.domElement]"
  />
</TresCanvas>
```

Or even deconstruct it

```html
<TresCanvas shadows alpha v-slot="{ camera, renderer }">
  <TresPerspectiveCamera :position="[5, 5, 5]" />
  <TresOrbitControls
    v-if="renderer"
    :args="[camera, renderer.domElement]"
  />
</TresCanvas>
```

### Suggested solution

Add this to `TresCanvas.vue`

```html
<canvas
    ref="canvas"
    :data-scene="scene.uuid"
    :class="$attrs.class"
    :data-tres="`tresjs ${pkg.version}`"
    :style="{
      display: 'block',
      width: '100%',
      height: '100%',
      position: windowSize ? 'fixed' : 'relative',
      top: 0,
      left: 0,
      pointerEvents: 'auto',
      touchAction: 'none',
      ...$attrs.style as Object,
    }"
 >
   <slot v-bind="context" />
</canvas>
```

### Additional context

related #565

### Validations

- [X] I agree to follow this project's [Code of Conduct](https://github.com/Tresjs/tres/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/Tresjs/tres/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://tresjs.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/tresjs/tres/issues) that reports the same bug to avoid creating a duplicate.

**Comment by andretchen0** [comment] 2024-03-04 21:12
Is the idea here just to get the renderer, etc.? Or also to get them?

----

Is this a duplicate of #573 ? If so, can we close there?

**Comment by userquin** [comment] 2024-03-04 22:00
it is duplicated, #573 has the hack (can be closed)

**Comment by andretchen0** [comment] 2024-03-04 23:25
@alvarosabu @userquin 

Are we talking about simply getting e.g., the renderer? Or also setting?

**Comment by userquin** [comment] 2024-03-04 23:29
it is only about using the context via default slot props, rn the example is not working since `state` is undefined, cannot use `useTresContext` since it can be only used via sfc children. Check linked issue and the hack in #573

**Comment by andretchen0** [comment] 2024-03-05 00:10
> it is only about using the context

So it's only for **getting**, right?

**Comment by userquin** [comment] 2024-03-05 00:56
Yes (like inject or exposed context prop)

**Comment by andretchen0** [comment] 2024-03-05 01:35
Can we use `defineExpose` instead?

We're using `defineExpose` for this sort of thing in Cientos and Tres most other places. Is there a reason it won't work here?

I do think it would be a welcome improvement to simplify the current TresCanvas' context `defineExpose` for v4 so that accessing the useful bits doesn't require a Demeter violation.

Any thoughts/opinions on using and simplifying `defineExpose` here?

----

## `<slot>`

Since we're not setting, only getting, I'm not sure about using the slot as suggested.
 
[From the Vue docs:](https://vuejs.org/guide/components/slots.html)

> We have learned that components can accept props, which can be JavaScript values of any type. But how about template content? In some cases, we may want to pass a template fragment to a child component, and let the child component render the fragment within its own template.

But we're not passing info to a child here, so it feels like a mismatch to use a `<slot>` to me.

**Comment by userquin** [comment] 2024-03-05 09:05
Rn context is exposed via `defineExpose`, check the hack, maybe we only need to update the code snippet.

**Comment by userquin** [comment] 2024-03-05 09:09
About the default slot: the problem is the custom renderer, it is adding custom stuff in the default slot, I will ask Kevin if we can retarget the slot using custom setup component when using the custom renderer.

**Comment by userquin** [comment] 2024-03-05 11:16
@alvarosabu @andretchen0 using default slot props in ExtendExample:

![imagen](https://github.com/Tresjs/tres/assets/6311119/ac96e9a5-c5d7-4228-8c4f-daec53b6b8dc)

![imagen](https://github.com/Tresjs/tres/assets/6311119/656123c0-e439-4d8c-9efb-7b2937369874)

![imagen](https://github.com/Tresjs/tres/assets/6311119/cb56c0de-2470-4558-85e9-1cedca9166f4)

![imagen](https://github.com/Tresjs/tres/assets/6311119/8d9d56be-6ac3-47a3-a0c4-e0e553d64019)

**Comment by userquin** [comment] 2024-03-05 11:31
Here the changes, update TresCanvas.vue in root and run build script from root, then start docs dev server once ExtendExample.vue and extending.md files updated:

<details>
<summary><strong>src/components/TresCanvas.vue</strong></summary>

```ts
// L84
const slots = defineSlots<{
  default(context: TresContext): any
}>()

const instance = getCurrentInstance()?.appContext.app

const createInternalComponent = (context: TresContext) =>
  defineComponent({
    setup() {
      const ctx = getCurrentInstance()?.appContext
      if (ctx) ctx.app = instance as App
      provide('useTres', context)
      provide('extend', extend)

      if (typeof window !== 'undefined' && ctx?.app) {
        registerTresDevtools(ctx.app, context)
      }
      return () => h(Fragment, null, slots?.default ? slots.default(context) : [])
    },
  })
```
</details>

<details>
<summary><strong>docs/.vitepress/theme/components/ExtendExample.vue</strong></summary>

```html
<script setup lang="ts">
import { TresCanvas, extend } from '@tresjs/core'
import { OrbitControls } from 'three/addons/controls/OrbitControls'
import { TextGeometry } from 'three/addons/geometries/TextGeometry'

// Add the element to the catalogue
extend({ TextGeometry, OrbitControls })
// import { useTresContext } from '@tresjs/core'

const styles = {
  width: '100%',
  height: '550px',
  border: '1px solid #e2e2e2',
  borderRadius: '8px',
  overflow: 'hidden',
}

// const { camera, renderer } = useTresContext()
</script>

<template>
  <ClientOnly>
    <TresCanvas
      v-slot="{ camera, renderer }"
      shadows
      xwindow-size
      clear-color="#fff"
      :style="styles"
    >
      <TresPerspectiveCamera :position="[0, 2, 4]" />
      <TresScene>
        <TresOrbitControls
          v-if="camera.value && renderer.value"
          :args="[camera.value, renderer.value.domElement]"
        />

        <TresDirectionalLight
          :position="[0, 2, 4]"
          :intensity="2"
          cast-shadow
        />
        <TresMesh :rotation="[-Math.PI / 4, -Math.PI / 4, Math.PI / 4]">
          <TresTorusGeometry :args="[1, 0.5, 16, 32]" />
          <TresMeshToonMaterial color="#FBB03B" />
        </TresMesh>
      </TresScene>
    </TresCanvas>
  </ClientOnly>
</template>
```
</details>

<details>
<summary><strong>docs/advanced/extending.md</strong></summary>

```md
# L36
<ClientOnly>
    <div style="aspect-ratio: 16/9; height: auto; margin: 2rem 0; border-radius: 8px; overflow:hidden;">
        <ExtendExample />
    </div>
</ClientOnly>
```
</details>

**Comment by andretchen0** [comment] 2024-03-05 22:24
Hey @alvarosabu @userquin !

> Rn context is exposed via defineExpose, check the hack

Sorry, I wasn't clear earlier.

I know that Tres is currently using `defineExpose` to make `context` available. I was wondering if cleaning up `context` and continuing to use `defineExpose` would be an acceptable alternative here.

That would be my preference.

## Rationale

The example of bad DX from #573 is indeed a bummer:

```vue
<script setup>
// [...]
const trescanvas = ref();
const state = ref();

onMounted(() => {
  setTimeout(() => {
    state.value = trescanvas.value?.context;
  }, 0);
});
// [...]
</script>

<template>
  <TresCanvas ref="trescanvas" shadows alpha>
    <TresPerspectiveCamera :position="[5, 5, 5]" />
    <TresOrbitControls
      v-if="state?.renderer"
      :args="[state?.camera, state?.renderer?.domElement]"
    />
    <!-- -->
  </TresCanvas>
</template>
```

But as far as I can see, it can be rewritten more simply and cover the presented use case. See below.

It seems to me that the code below isn't materially different from the bad DX example. It only needs one extra line in `<script setup>` – a `ref`. It works with the current `main` branch of Tres.

(Fwiw, [`extend` in the latest release is throwing errors for me](https://github.com/Tresjs/tres/issues/565), so I can't recreate the bad DX example as written, but I've tried to recreate the salient parts without `extend` below.)

```vue
<script setup lang="ts">
import { TresCanvas } from '@tresjs/core'
import { ref } from 'vue'

// NOTE: TS likes to know the "shape" or the editor will complain.
const r = ref({ context: { renderer: { value: null } } }) 
</script>

<template>
  <div style="height:50%">
    <TresCanvas ref="r" clear-color="#82DBC5">
      <TresMesh>
        <TresBoxGeometry :args="[1, 1, 1]" />
        <TresMeshNormalMaterial />
      </TresMesh>
    </TresCanvas>
  </div>
  <div>
    <div v-if="r.context.renderer.value">
      We have a renderer: {{ Object.keys(r.context.renderer.value) }}
    </div>
    <div v-else>
      We don't have a renderer.
    </div>
  </div>
</template>
```

[StackBlitz
](https://stackblitz.com/edit/tresjs-basic-kugjtq?file=src%2Fcomponents%2FTheExperience.vue)

## Preference: `defineExpose`

If I've understood the issue here correctly and if it's true that we can reduce the bad DX example to one extra line of code, my preference would be to stick with `defineExpose` and reserve `<slot>`s for [use cases as defined in the Vue docs](https://vuejs.org/guide/components/slots.html), e.g., we have a template fragment to send to a child for rendering.

Maybe we could smooth out what's `defineExpose`d for v4 so that we can e.g., just use `r.renderer` in the code above.

## Moving forward

I don't want to impede forward progress. If I've misunderstood something here, please let me know. Otherwise, @alvarosabu , I'll leave the final call up to you.

**Comment by userquin** [comment] 2024-03-06 09:35
What's the problem using the default slot and exposing props? We can also add some logic to render children when camera and renderer there and provide just the camera and renderer without refs.

**Comment by andretchen0** [comment] 2024-03-06 17:28
> What's the problem using the default slot 

If you're responding to me, then [please see my earlier comment.](https://github.com/Tresjs/tres/issues/572#issuecomment-1979739044)

> We can also add some logic to render children when camera and renderer there and provide just the camera and renderer without refs.

I don't think it's a bad idea, but it has much bigger implications than this DX issue.

I'd like to let the team have a chance to discuss this in a broader context, so I've opened a new discussion about the core and mentioned you there. #578 I've laid out what I think are the related open issues, including this one.

**Closed** 2024-06-01 07:39 UTC
Labels: wontfix, has-workaround
