### ISSUE TITLE
`<TresSprite @click="() => console.log('')" />` throws error on pointer interaction

### ISSUE THREAD

**Issue by andretchen0** [Tresjs/tres#527] opened 2024-01-29 11:37 UTC
### Describe the bug

When ...

```
<TresSprite @click="(e) => { console.log('ok', e); }" />
``` 

... is moused over, it throws this error:

```
Uncaught TypeError: proxy must report the same value for the non-writable, non-configurable property '"modelViewMatrix"'
```

### Expected

`@click` should work normally and not throw an error.

### Reproduction

[StackBlitz](https://stackblitz.com/edit/tresjs-basic-agjgk5?file=src%2Fcomponents%2FTheExperience.vue)

### Additional context

* [Working example in plain Three.js for comparison.](https://stackblitz.com/edit/three-js-start-ujyp75?file=index.ts)
* [Discussion thread of Vue proxy error on discourse.threejs.org](https://discourse.threejs.org/t/migration-from-vuejs-2-to-3-not-working-due-to-render/22374/7)

### System Info

```shell
System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 18.18.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 10.2.3 - /usr/local/bin/npm
    pnpm: 8.14.0 - /usr/local/bin/pnpm
  npmPackages:
    @tresjs/cientos: ^3.5.1 => 3.5.1 
    @tresjs/core: ^3.4.1 => 3.4.1 
    @tresjs/eslint-config-vue: ^0.2.1 => 0.2.1 
    vite: ^4.5.0 => 4.5.0
```

### Used Package Manager

npm

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/Tresjs/tres/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/Tresjs/tres/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://tresjs.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/tresjs/tres/issues) that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by garrlker** [comment] 2024-01-29 23:56
Replying here to keep the main thread clean as well

1st, thank you for making this issue and reproduction! Your questions and repros are helping me a ton!

2nd, 
The solution I've been working on for #515 for abstracts the parts of the event system so we support events for everything in the scene, not just Object3Ds. Originally I had made that change to support event's on `primitives`, *BUT*, It looks like those changes allow for `TresSprite` events to work as well

<img width="1208" alt="image" src="https://github.com/Tresjs/tres/assets/7344576/3cfb9f26-3913-4f51-9b58-43da9d80f0b3">

Copied your reproduction into my local and it worked first try

**Comment by andretchen0** [comment] 2024-01-30 18:34
@garrlker Sure thing! Let me know if there's anything I can help with on #515.

**Comment by garrlker** [comment] 2024-01-31 05:50
@andretchen0 I've got my draft PR up, #529, I would love if you could give it a thorough look over when you get a chance?

**Comment by alvarosabu** [comment] 2024-05-30 06:50
Hi @andretchen0 can you please check if this still the case in v4 after @garrlker changes? If not please close it

**Comment by alvarosabu** [comment] 2024-08-21 10:45
Close due inactivity. Feel free to re-open if needed.

**Closed** 2024-08-21 10:44 UTC
Labels: waiting for author
