### ISSUE TITLE
`TresPerspectiveCamera` `lookAt` not working with `CameraControls`

### ISSUE THREAD

**Issue by wcheek** [Tresjs/tres#760] opened 2024-07-05 06:39 UTC
### Describe the bug

I want my camera to look at a position. `TresPerspectiveCamera` has a [`look-at`](https://docs.tresjs.org/api/instances-arguments-and-props.html#methods) prop that uses the [`lookAt`](https://threejs.org/docs/#api/en/core/Object3D.lookAt) method of `Object3D` to point the camera at a position, but when used alongside the [`cientos` `CameraControls` component](https://cientos.tresjs.org/guide/controls/camera-controls.html) the functionality is lost.

### Reproduction

https://stackblitz.com/edit/tresjs-minimal-reproduction-iazqxl?file=src%2Fcomponents%2FTheExperience.vue,package.json,src%2FApp.vue

### Steps to reproduce

Use `CameraControls` with `TresPerspectiveCamera` and set the `look-at` prop.

### Used Package Manager

npm

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/Tresjs/tres/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/Tresjs/tres/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://tresjs.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/tresjs/tres/issues) that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by alvarosabu** [comment] 2024-07-05 06:45
Hi @wcheek thanks for taking the time to create the ticket and adding a proper reproduction. 

Maybe @JaimeTorrealba can help us here, I think controls in general affect the look-at property of the camera right?

**Comment by wcheek** [comment] 2024-07-05 06:45
Here's a hack that is working for me using the [`setLookAt` method of `CameraControls`](https://yomotsu.github.io/camera-controls/classes/CameraControls.html#setLookAt) that I fire once the `cameraRef` gets populated.

```ts
const cameraRef: ShallowRef<TresObject | null> = shallowRef(null);

watch(cameraRef, () => {
  cameraRef.value!.value.setLookAt(
    // first 3 args are the position
    position[0],
    position[1],
    position[2],
    target[0],
    target[1],
    target[2],
    // Smooth transition
    false,
  );
});

      <CameraControls ref="cameraRef" />
```

**Comment by Neosoulink** [comment] 2024-07-12 05:50
Hello @alvarosabu, is someone planning to work on this ticket?
I can investigate and work on it

**Comment by alvarosabu** [comment] 2024-08-21 10:46
Hi @Neosoulink we would highly appreciate it if you could help us here.

**Comment by alvarosabu** [comment] 2024-08-21 10:47
@wcheek could you please add a small reproduction link to help the team work on this better? Thanks

**Comment by Neosoulink** [comment] 2024-08-21 20:26
> Hi @Neosoulink we would highly appreciate it if you could help us here.

Sure thing @alvarosabu, I'm giving it a shot

**Comment by wcheek** [comment] 2024-08-21 23:49
[Here](https://stackblitz.com/edit/tresjs-minimal-reproduction-iazqxl?file=src%2Fcomponents%2FTheExperience.vue,package.json,src%2FApp.vue) is the reproduction link again - I've upgraded to `latest` `"@tresjs/cientos": "^4.0.0", "@tresjs/core": "^4.2.0"` and seeing the same issue.

**Comment by Neosoulink** [comment] 2024-08-24 14:05
Hey @wcheek @alvarosabu,
I'm coming back with some good news!

The problem that you're facing @wcheek is not really an issue but a normal behavior

#### Explanation

The [camera-controls](https://github.com/yomotsu/camera-controls?tab=readme-ov-file#gettarget-out-receiveendvalue-) has its own target point, just like the [OrbitControls.target](https://threejs.org/docs/?q=orbi#examples/en/controls/OrbitControls.target), when you use it, you have to update the target `OrbitControl` (or `CameraControl`) target.

Here's the way of setting the target (or the **LookAt** feature):

```vue
<script setup lang="ts">
const target = shallowRef(new Vector3(0, 0.5, 0));
const cameraRef = shallowRef(null);
const cameraControlRef = shallowRef(null);

onLoop(() => {
  cameraControlRef?.value?.instance?.setTarget?.(
    target.value.x,
    target.value.y,
    target.value.z
  );
});
</script>

<template>
  <!-- Start of the code... -->
    <TresPerspectiveCamera ref="cameraRef" />
    <CameraControls ref="cameraControlRef" />
  <!-- Rest of the code... -->
</template>
```
> Here's the complete example:
> [Tresjs-minimal-cameraControl-LookAt](https://stackblitz.com/edit/tresjs-minimal-reproduction-swzwge?file=src%2FApp.vue)

#### Other solutions

As I said above, this is a completely normal behavior and, there are no bugs, however, we can add a new feature to the [Cientos | CameraControls](https://cientos.tresjs.org/guide/controls/camera-controls.html) to support by default the `lookAt` of the current active camera

We could have something like: ` <CameraControls useCaremaTarget />`

Let me know if this helps...

**Comment by alvarosabu** [comment] 2024-08-30 07:20
Thanks @Neosoulink for the feedback. Since is expected behavior and it has a work-around, I'm gonna close this ticket.

**Closed by alvarosabu** 2024-08-30 07:20 UTC
Labels: pending-triage, needs reproduction
