### ISSUE TITLE
Cannot read properties of undefined (reading 'dispose') - GridHelper

### ISSUE THREAD

**Issue by whitespacecode** [Tresjs/tres#721] opened 2024-06-05 12:48 UTC
### Describe the bug

When i try to show/hide the GridHelper i get a TypeError. The code still works. 
I tried it on an older tresjs version and no typeError happend.

`<TresGridHelper v-if="gridHelper.visible" :args="[10, 100, 0xff0000]" />`
![image](https://github.com/Tresjs/tres/assets/37139936/e717d837-9f3d-45fe-8c4e-59d70c67afac)

Not sure if that is also the case for other components.

### Reproduction

https://stackblitz.com/edit/tresjs-basic-hfgtuj

### Steps to reproduce

Use the reproduction, click on the button 'Toggle Grid' and check the console logs.

### System Info

```shell
System:
    OS: macOS 14.3.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 90.73 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.18.0 - ~/.nvm/versions/node/v18.18.0/bin/node
    Yarn: 1.22.21 - ~/.nvm/versions/node/v18.18.0/bin/yarn
    npm: 10.6.0 - ~/Code/Modulab/node_modules/.bin/npm
  Browsers:
    Chrome: 125.0.6422.142
  npmPackages:
    @tresjs/cientos: ^3.9 => 3.9.0
    @tresjs/core: ^4.0.2 => 4.0.2
    vite: ^5.2.10 => 5.2.10
```

### Used Package Manager

npm

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/Tresjs/tres/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/Tresjs/tres/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://tresjs.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/tresjs/tres/issues) that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by garrlker** [comment] 2024-06-07 04:20
Looks like we're calling `.dispose()` twice when this is removed from the scene. Easy fix, though it's interesting how this bug got in

**Comment by alvarosabu** [comment] 2024-07-03 13:52
@andretchen0 is this solved by the disposal refactor?

**Comment by andretchen0** [comment] 2024-07-03 16:33
@alvarosabu 

> is this solved by the disposal refactor?

Most likely. I will make a test from the reproduction and add it to the nodeOps tests.

**Comment by andretchen0** [comment] 2024-07-04 16:33
Following up, this is indeed a problem with Tres `nodeOps` (Vue's `RendererOptions`) `remove`.

This test against `main` currently fails:

```ts
  it('disposes a GridHelper', () => {
    const gridHelper = nodeOps.createElement('TresGridHelper', undefined, undefined, {})
    expect(() => nodeOps.remove(gridHelper)).not.toThrow()
  })
```

**Comment by andretchen0** [comment] 2024-07-04 17:22
@garrlker 

I see you're assigned here. You're free to keep working on it, but fwiw, the issue is fixed in a soon-to-be submitted PR dealing with primitive/disposal. 

When I submit, I'll mark that PR as closing this issue, if that's ok.

**Comment by andretchen0** [comment] 2024-07-08 20:38
Just for future reference, it *is* interesting:

> Looks like we're calling `.dispose()` twice when this is removed from the scene. Easy fix, though it's interesting how this bug got in

The bug stems from these 2 competing disposals:

* THREE creates the `GridHelper` and *knows* it has a material and geometry. So when its `dispose` method is called, the THREE code tries to `this.material.dispose()`.
* Tres disposes from the bottom up. Children are disposed and detached before parents.

Combine these 2 and you see that by the time the THREE `dispose` runs, the `GridHelper` no longer has a `material` or `geometry`. So e.g., `this.material.dispose()` will throw, because `this.material` is `undefined`.

**Closed** 2024-07-10 11:24 UTC
Labels: p2-edge-case
