### ISSUE TITLE
The @pointer-move function experiences noticeable lag

### ISSUE THREAD

**Issue by hawk86104** [Tresjs/tres#436] opened 2023-11-07 02:51 UTC
### Describe the bug

The @pointer-move function experiences noticeable lag when the [widthSegments | heightSegments] of PlaneGeometry exceeds 100.

### Reproduction

https://stackblitz.com/edit/tresjs-basic-bxhf8j?file=src%2Fcomponents%2FTheExperience.vue

### Steps to reproduce

```
<TresMesh @pointer-move="onPointerMove">
  <TresPlaneGeometry :args="[50, 50, 200, 200]" />
  <MeshBasicMaterial />
</TresMesh>
```

### Used Package Manager

yarn

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/Tresjs/tres/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/Tresjs/tres/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://tresjs.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/tresjs/tres/issues) that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by CptJJ** [comment] 2023-11-21 21:47
@alvarosabu this is probably related to what I was talking about on discord, i only see the lag come up when i bind any of the events (even onClick) to a mesh that has several hundred triangles:
<img width="563" alt="image" src="https://github.com/Tresjs/tres/assets/5834717/dc6418be-cf30-49aa-8225-bef8f78faa0f">

**Comment by alvarosabu** [comment] 2023-11-23 18:36
Thnx both for raising this @hawk86104 @CptJJ

**Comment by Sea-DH1** [comment] 2023-12-12 17:56
I have encountered this problem before. I checked the code and finally found that if three-mesh-bvh is used, this problem no longer exists.

**Comment by alvarosabu** [comment] 2023-12-13 08:53
@Tinoooo @garrlker maybe this would be fixed by the changes you guys are doing on events?

**Comment by hawk86104** [comment] 2023-12-14 07:35
Thank you, it has indeed solved the problem



| |
hawk
|
|
***@***.***
|


---- Replied Message ----
| From | Alvaro ***@***.***> |
| Date | 12/13/2023 16:53 |
| To | ***@***.***> |
| Cc | ***@***.***> ,
***@***.***> |
| Subject | Re: [Tresjs/tres] The @pointer-move function experiences noticeable lag (Issue #436) |

@***@***.*** maybe this would be fixed by the changes you guys are doing on events?

**Comment by CptJJ** [comment] 2023-12-15 07:28
Amazing Fixed It!

Is there a downside to making this the default when rendering meshes in tres?

**Comment by alvarosabu** [comment] 2023-12-15 08:34
Glad to hear it has been solved, @CptJJ what do you mean on making it default?

**Comment by garrlker** [comment] 2024-04-27 19:51
@alvarosabu @hawk86104 

It looks like the Tres V4 RC fixes the issues in the original stackblitz

[Here's a fork](https://stackblitz.com/edit/tresjs-basic-gzdcqf?file=package.json) that updates to the V4 RC and does not show the same performance issues

If you don't mind @hawk86104, could you temporarily disable the three-mesh-bvh code in your project and let us know if the issue is fixed?

**Comment by hawk86104** [comment] 2024-04-29 07:27
> @alvarosabu @hawk86104
> 
> It looks like the Tres V4 RC fixes the issues in the original stackblitz
> 
> [Here's a fork](https://stackblitz.com/edit/tresjs-basic-gzdcqf?file=package.json) that updates to the V4 RC and does not show the same performance issues
> 
> If you don't mind @hawk86104, could you temporarily disable the three-mesh-bvh code and try out the V4 RC in your project and let us know if the issue is fixed?
> 
> `yarn i @tresjs/core@4.0.0-rc.0`

@garrlker  You're very welcome! That's great to hear. I'm not sure when it will be merged into the main branch.

**Comment by Rain20199** [comment] 2024-05-09 02:59
@tresjs/core@4.0.0-rc.0   pointer events trigger multiple times

**Comment by garrlker** [comment] 2024-05-09 06:08
@Rain20199 They do? 

That's strange, we do check for duplicate events and ignore a handler if we've already called it

Any chance you could make a reproduction so I can look into it?

**Comment by alvarosabu** [comment] 2024-05-09 06:40
@Rain20199 since it is a different issue can you open a new ticket with a minimal reproduction? Thanks

**Closed by alvarosabu** 2024-05-09 06:40 UTC
Labels: bug, help wanted, performance
